### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by attarwang** [caprica/vlcj-javafx-demo#2]
```
JNA: Callback uk.co.caprica.vlcj.player.direct.DefaultDirectMediaPlayer$DisplayCallback@1d1e765 threw the following exception:
java.lang.OutOfMemoryError: Java heap space
    at javafx.scene.canvas.GraphicsContext$1.setPixels(GraphicsContext.java:1780)
    at uk.co.caprica.vlcj.javafx.test.JavaFXDirectRenderingTest$TestMediaPlayerComponent.display(JavaFXDirectRenderingTest.java:158)
    at uk.co.caprica.vlcj.player.direct.DefaultDirectMediaPlayer$DisplayCallback.display(DefaultDirectMediaPlayer.java:280)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:455)
    at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:485)
```

**Comment by migralito** [comment]
Hey guys!
Has there been any other problem like this?
I’m facing a very similar issue, with visualvm graphs pretty much the same (going very high very quickly). I’m using canvas->graphics context->pixel writer, but I don’t know how to avoid it in JavaFX. It seems to be the only way. I switch to using Image class instead of canvas, but it also uses pixel writer. It looks like the direct memory access is indeed the pixel writer approach. I would be really thankful if there’s anything new regarding this behavior.
Thanks, Alex

**Comment by caprica** [comment]
I can't add anything new. My own profiling as documented above showed no memory leak.

So you need to do your own profiling, and see which objects are still living in your heap. I can't do that for you.

**Comment by migralito** [comment]
Is it normal that logs says the following just before the start of the stream?

> 10:35:20.616 [Finalizer] DEBUG u.c.c.v.player.AbstractMediaPlayer - finalize()
> 10:35:20.623 [Finalizer] DEBUG u.c.c.v.player.AbstractMediaPlayer - Media player has been garbage collected
> 10:35:20.625 [Finalizer] DEBUG u.c.c.v.player.AbstractMediaPlayer - finalize()
> 10:35:20.626 [Finalizer] DEBUG u.c.c.v.player.AbstractMediaPlayer - Media player has been garbage collected
> 10:35:20.626 [Finalizer] DEBUG u.c.c.v.player.AbstractMediaPlayer - finalize()
> 10:35:20.626 [Finalizer] DEBUG u.c.c.v.player.AbstractMediaPlayer - Media player has been garbage collected
> 10:35:20.626 [Finalizer] DEBUG u.c.c.v.player.AbstractMediaPlayer - finalize()
> 10:35:20.626 [Finalizer] DEBUG u.c.c.v.player.AbstractMediaPlayer - Media player has been garbage collected
>

**Comment by caprica** [comment]
Well, it depends... Which code are you running to see that in the logs? Is it your own application?

**Comment by migralito** [comment]
yes, after
`playerComponent.getMediaPlayer().startMedia(url)`
in which playerComponent is an instance of DirectMediaPlayerComponent

**Comment by caprica** [comment]
Yes, but is this happening your own code, in your own application?

**Comment by migralito** [comment]
Yes it is

**Comment by caprica** [comment]
Well, you need to work out why your media players are being garbage collected. I can't do that.
