### ISSUE TITLE
Wrong Thread errors

### ISSUE THREAD

**Issue by rihlsul** [caprica/vlcj-javafx-demo#3]
I snagged a copy of vlcj-javafx.  I'm running it with the JDK8 release (1.8.0-ea-b112) and I get some issues trying it out:

```
JNA: Callback uk.co.caprica.vlcj.player.direct.DefaultDirectMediaPlayer$SetupCallback@e93bcb7 threw the following exception:
java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-25
    at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:209)
    at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:393)
    at javafx.scene.Scene.addToDirtyList(Scene.java:516)
    at javafx.scene.Node.addToSceneDirtyList(Node.java:418)
    at javafx.scene.Node.impl_markDirty(Node.java:409)
    at javafx.scene.canvas.Canvas.access$000(Canvas.java:74)
    at javafx.scene.canvas.Canvas$1.invalidated(Canvas.java:141)
    at javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:112)
    at javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:146)
    at javafx.scene.canvas.Canvas.setWidth(Canvas.java:128)
    at uk.co.caprica.vlcj.javafx.test.JavaFXDirectRenderingTest$TestBufferFormatCallback.getBufferFormat(JavaFXDirectRenderingTest.java:185)
```

**Comment by jdub1581** [comment]
Just want to throw my 2 cents in .. 
Rather than using a Timeline for the updates, it makes more sense to me to do something like so:

```
     ObjectProperty< -InfoFromCallback- > renderProperty = new SimpleObjectProperty<>(){
             @Override
             public void invalidated(Observable o){
                 if(conditions){
                      pixelWriter.setPixels(0, 0, 
                             currentFormat.getWidth(),
                             currentFormat.getHeight(),
                             pixelFormat, currentBuffer,
                             currentFormat.getWidth()*4);
             }                               
          }                
     };
```

Invalidated is always called on FX thread, and is much faster than adding a listener. I do a lot of 3D with javafx and Mesh updates are a bear, but this approach updates are very fast, and no threat of "wrong thread"  ...

**Comment by caprica** [comment]
OK, so in principle I like that approach better - I was never happy with the Timeline.

But...

I'm still not clear on *all* of the threading semantics with that approach - this is not just about wrong thread errors for JavaFX. With the code you posted, your invalidate method looks to me like it is still accessing the native buffer in an un-synchronised way (so you might render corrupted frames).

The *native* buffer must be locked at the time your application *renders* the frame, unless your callback is copying the frame which I doubt.

I mean, I need to see a full example in context to understand it and make sure it's OK, not just this fragment.

**Comment by caprica** [comment]
After looking at this in more detail, I'm somewhat sceptical, but I'm not a pro JavaFX developer so perhaps I missed something.

The object property must be set on the JavaFX thread, otherwise a wrong thread error is raised.

If I use Platform.runLater inside my callback to update that value, I see a fatal JVM crash and no video.

On the other hand, the Timeline solution works just fine.

I would be very happy to recommend some way other than using the Timeline, but right now I can't see it.

**Comment by jdub1581** [comment]
Yes I realized that after I went to try it on an "old" (pre jdk 8) build... So I will offer an approach that I used on a Cloth simulator (3D) .. 

https://www.youtube.com/watch?v=uRsCcpbsdsg 

Basically create a loop timer, It is ran in the background, and updates ui on completion .. 

```
    /**
 *
 * @author jdub1581
 */
public class NanoTimer extends ScheduledService<Void> {

    private final long ONE_NANO = 1000000000L;
    private final double ONE_NANO_INV = 1f / 1000000000L;

    private long startTime, previousTime;
    private double frameRate, deltaTime;
    private final NanoThreadFactory tf = new NanoThreadFactory();

    int cAcc = 3;

    public NanoTimer() {
        super();
        this.setPeriod(Duration.millis(16));// equivalent to 60 fps
        this.setExecutor(Executors.newCachedThreadPool(tf));
    }

    public double getTimeAsSeconds() {
        return getTime() * ONE_NANO_INV;
    }

    public long getTime() {
        return System.nanoTime() - startTime;
    }

    public long getOneSecondAsNano() {
        return ONE_NANO;
    }

    public double getFrameRate() {
        return frameRate;
    }

    public double getDeltaTime() {
        return deltaTime;
    }

    private void updateTimer() {
        deltaTime = (getTime() - previousTime) * (1.0f / ONE_NANO);
        frameRate = 1.0f / deltaTime;
        previousTime = getTime();

    }

    @Override
    public void start() {
        super.start();
        if (startTime <= 0) {
            startTime = System.nanoTime();
        }
    }

    @Override
    public void reset() {
        super.reset();
        startTime = System.nanoTime();
        previousTime = getTime();
    }

    @Override
    protected Task<Void> createTask() {
        return new Task<Void>() {
            @Override
            protected Void call() throws Exception {                
                updateTimer();
                // non fx thread updates ...
                                


                return null;
            }
        };
    }

    @Override
    protected void succeeded() {
        super.succeeded();
        //update the UI here
    }

    @Override
    protected void failed() {
        getException().printStackTrace(System.err);

    }

    @Override
    public String toString() {
        return "ElapsedTime: " + getTime() + "\nTime in seconds: " + getTimeAsSeconds()
                + "\nFrame Rate: " + getFrameRate()
                + "\nDeltaTime: " + getDeltaTime();
    }

    /*==========================================================================
        creates a daemon thread for use
     */
    private class NanoThreadFactory implements ThreadFactory {

        public NanoThreadFactory() {
                 // add other data if need be
        }

        @Override
        public Thread newThread(Runnable r) {
            Thread t = new Thread(r, "NanoTimerThread");
            t.setDaemon(true);
            return t;
        }

    }
}//=============================================================================
``` 
Can either use a property as I said and set that property in the OnSucceeded or try directly, also
you can take all the Time updates out I'm sure.. Performance was increased 2x in my simulation,
so I think with some cleverness the same could happen here ...

**Comment by caprica** [comment]
Thanks for posting that, I'll try investigating this approach some more...

**Comment by caprica** [comment]
After testing this, it is *much* smoother than the ObjectProperty approach. In fact, the video playback looks absolutely perfect to me.

Time now to do some CPU profiling I guess...

**Comment by jdub1581** [comment]
That's awesome to hear ! 
Note that there are other settings in the scheduled service that should probable be addressed, 
like setting a backoff strategy, set to restart on fault maybe? and others.. also playing with the executor as well, maybe a single threaded one would be more appropriate.
This was the best way I found to make a thread loop in javafx..

**Comment by caprica** [comment]
Some very naive preliminary CPU profiling shows for me both the Timeline solution and the NanoTimer solution use on average between 5% and 6% CPU. There's no discernible difference between the two approaches in terms of CPU usage, at least not for me (i7-3770k).

**Comment by caprica** [comment]
I think someone who knows JavaFX better than me could make the NanoTimer work more optimally with vlcj, especially taking into account your latest comment. I wouldn't know where to being with backoff strategy and so on.

**Comment by jdub1581** [comment]
I think the main difference is when and how they get scheduled in the back end. Timeline has to go through a few more hoops, which is probably where that micro delay was happening. I'd also try playing with the "period" maybe more less?

And yeah, I believe the backoffStrat is just another task to run in case of too many failures..
Which you should probably add some record keeping to the Timer .. And maybe some atomic locks ..

**Comment by caprica** [comment]
Clearly you know this stuff better than me. :-)

**Comment by jdub1581** [comment]
trial and error, trial and error ... :)

**Comment by caprica** [comment]
Your 3D Cloth simulator is pretty damn impressive.

**Comment by caprica** [comment]
OK, so I committed a naive implementation using this nano timer to the vlcj-javafx project.

Maybe it can be improved, but right now it works and should help people integrating vlcj into their JavaFX application.

In my own tests, I was able to render full HD at 60fps using a peak of 15% CPU, which seems pretty good to me.

**Comment by jdub1581** [comment]
Awesome bud, just glad there was an improvement.. guess I'll have to
re-make my player now as well ;)  (haven't touched it in a year or so (-_-)
<--)

**Comment by jdub1581** [comment]
As I thought about it, if you want to try, you could also use the same concept in an AnimationTimer ..
It's a 60fps loop as well. In the vlc callback just set a boolean flag for when ready to render,
in the timer have an  if(ready){writePixels();} .. may be just as viable..

**Comment by caprica** [comment]
I think a flag is not *really* needed, the timer action can just lock the native buffer and render whatever's there.

**Comment by caprica** [comment]
OK, I added a new test with a naive AnimationTimer implementation.

The playback looks pretty smooth to me.

This is clearly the simplest way to do it, in terms of code anyway.
