### ISSUE TITLE
positionChanged event when position is set while paused

### ISSUE THREAD

**Issue by GeePawHill** [caprica/vlcj-javafx-demo#33]
The positionChanged event fires only when the video is playing. If the video is paused, and setPosition is called, it does not fire.

MRE: Take any animation mode, add a handler for positionChanged to the existing MediaEventListener that spits something to the console. While a plays, it emerges about every second. When the video is paused, it never fires.

Thanks,
GeePaw

**Comment by caprica** [comment]
As per #32, this works with VLC 4.

Sorry that's not the answer you might want right now, but events are delivered from the native application - vlcj would send you the event if VLC sent it, but in VLC 3 it doesn't (always).

**Comment by GeePawHill** [comment]
No worries, I can wait for VLC4. Thanks for the quick reply!
