### ISSUE TITLE
play the next video，there is a memory leak.

### ISSUE THREAD

**Issue by huangzhiv** [caprica/vlcj-javafx-demo#37]
Hi, Caprica.
In the ubuntu20.04 system, the default installation of vlc3.0.9,  I use vlcj4.6.0 and jdk11 javafx15. When I play the next video, there is a memory leak. 
Can you help me in this case. Thanks you so much.

**Comment by caprica** [comment]
If you have evidence of *vlcj* being responsible for your leaking memory, post that evidence.

It's been a while since I did test vlcj for memory leaks, but the last time I did test there were no leaks. vlcj was running in under 20mb of memory for many hours IIRC.

**Comment by caprica** [comment]
And to be honest, if your complaining about this JavaFX demo application leaking memory, well, I'm not too concerned. This particular project is just a demo after all and not a fully robust product.

In my experience, JavaFX itself can be responsible for memory leaks.

But without evidence I don't know what you expect me to do.

**Comment by huangzhiv** [comment]
> It's been a while since I did test vlcj for memory leaks, but the last time I did test there were no leaks. vlcj was running in under 20mb of memory for many hours IIRC

Thank you for your reply. 
This is my code. I wrote it after demo, and add the code“ embeddedMediaPlayer.controls ().setRepeat(true)"; I use the "top" command to monitor running memory. When the video plays again, Memory will increase. I'm not sure where the problem is, or my Ubuntu environment. 

`package vlcj;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.image.ImageView;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.layout.Pane;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import uk.co.caprica.vlcj.factory.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.base.MediaPlayer;
import uk.co.caprica.vlcj.player.base.MediaPlayerEventAdapter;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

import static uk.co.caprica.vlcj.javafx.videosurface.ImageViewVideoSurfaceFactory.videoSurfaceForImageView;


public class MyFxPlayer extends Application {
    private final MediaPlayerFactory mediaPlayerFactory;
    private final EmbeddedMediaPlayer embeddedMediaPlayer;
    private ImageView videoImageView;

    public MyFxPlayer() {
        this.mediaPlayerFactory = new MediaPlayerFactory();
        this.embeddedMediaPlayer = mediaPlayerFactory.mediaPlayers().newEmbeddedMediaPlayer();
        this.embeddedMediaPlayer.events().addMediaPlayerEventListener(new MediaPlayerEventAdapter() {
            @Override
            public void playing(MediaPlayer mediaPlayer) {
            }

            @Override
            public void paused(MediaPlayer mediaPlayer) {
            }

            @Override
            public void stopped(MediaPlayer mediaPlayer) {
                System.out.println("stop");
            }

            @Override
            public void finished(MediaPlayer mediaPlayer) {
                System.out.println("finish");
            }

            @Override
            public void error(MediaPlayer mediaPlayer) {
                System.out.println("error");
            }

            @Override
            public void timeChanged(MediaPlayer mediaPlayer, long newTime) {

            }
        });
    }

    @Override
    public void start(Stage primaryStage) {

        Pane root = new Pane();
        root.setStyle("-fx-background:transparent;");

        videoImageView = new ImageView();
        videoImageView.setPreserveRatio(true);
        embeddedMediaPlayer.videoSurface().set(videoSurfaceForImageView(this.videoImageView));
        embeddedMediaPlayer.controls().setRepeat(true);
        root.getChildren().add(videoImageView);

        Scene scene = new Scene(root, Color.BLACK);

        primaryStage.setScene(scene);
        primaryStage.setFullScreen(true);
        primaryStage.setFullScreenExitHint("");
        primaryStage.setTitle("myPlayer");
        primaryStage.initStyle(StageStyle.TRANSPARENT);
        primaryStage.show();

        String fullUrl = "/home/pis-player/plan/A870F0528FFBB9E4E0552A9E97DB6358/495cdf20641742c48745c4fc0c045695.mp4";
        embeddedMediaPlayer.media().play(fullUrl);
    }

}
`

**Comment by huangzhiv** [comment]
My issue is solved. The reason is that I didn't add Maven dependencies of guava.  
`<dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>28.2-jre</version>
        </dependency>`
It seems that the work is normal, but the memory leak is caused by the missing dependency. This problem has been bothering me for a week. I'm glad to have solved this problem. 
Thank you for your time, Thanks you so much.
