### ISSUE TITLE
setRate make screen pause

### ISSUE THREAD

**Issue by pkxutao** [caprica/vlcj-javafx-demo#45]
5.0.0-SNAPSHOT + vlc 4.0 in branch 5.x 
i call `mediaPlayer.controls().setRate(3);` in PlayerView, the screen paused,but the TimelineComponent still move

**Comment by caprica** [comment]
Probably you need to check the native logs.

Create a MediaPlayerFactory with "-vvv" in the arguments list and see what the log output says.

It might simply be that the media can't be reliably played at that rate via the software rendering callbacks.

**Comment by caprica** [comment]
I can only surmise your CPU can't process the frames quickly enough to play at that rate.
Remember, JavaFX is _software_ rendering video, you are CPU-limited.
